Bump pkl.impl.ghactions to version 1.8.1 (#39)
Updates pkl.impl.ghactions package to version 1.8.1

diff --git a/.github/workflows/prb.yml b/.github/workflows/prb.yml
--- a/.github/workflows/prb.yml
+++ b/.github/workflows/prb.yml
@@ -51,14 +51,18 @@ jobs:
         echo "pkl_exec=$PKL_EXEC" >> "$GITHUB_OUTPUT"
     - run: pkl format --diff-name-only .
   verdict:
-    if: '!cancelled() && !failure()'
+    if: always()
     needs:
     - check-pkl-github-actions
     - build-and-test
     - test-pkl-formatting
     runs-on: ubuntu-latest
     steps:
-    - run: 'true'
+    - name: Failure verdict
+      if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
+      run: |-
+        echo "Some of the required jobs are either failing or were cancelled"
+        exit 1
   upload-event-file:
     runs-on: ubuntu-latest
     steps:
